[package]
name = "gtk-4-rust-template"
description = ""
version = "0.1.0"
authors = ["You <you@example.com>"]
readme = "README.md"
edition = "2021"

[dependencies]
ferris-says = "0.3.1"
gtk = { version = "0.9.6", package = "gtk4", features = ["v4_16"] }
